name: "Factorio Mod Uploader"
description: "Create a zip file from a Factorio mod source."
author: "Henrique Gemignani Passos Lima <henrique@gemignani.org>"
branding:
  icon: "package"
  color: "green"

inputs:
  zip_file:
    description: "Specify the path to the zip file to upload"
    required: true
  
  api_key:
    description: "An Factorio.com API Key. Create at https://factorio.com/create-api-key"
    required: true

  validate_only:
    description: "If true, will only perform the changelog validation"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Dependencies
      shell: bash
      run: python -m pip install requests

    - name: Upload
      shell: bash
      run: python uplader.py
        